### ISSUE TITLE
Can we set `max_ev_time` different for each binary?

### ISSUE THREAD

**Issue by TomWagg** [TomWagg/cosmic-gala#1]
This'll be a question for @katiebreivik.

I'm currently evolving every binary in COSMIC for 13.7 billion years - **this is not correct** given that they each have different birth times. We should account for this. Either:

1. Maybe there's a method in COSMIC to just set the `max_ev_time` individually 🤞🏻 
2. Or, we do something sneaky like force `bcm` to include a timestep of an exact time for each binary perhaps?

**Comment by TomWagg** [comment]
I thought that if I were to update the values of `tphys` for each of the initial binaries this might solve it but this seems to make it so that only one line of output is given in `bpp` rather than one for each kstar...

**Comment by katiebreivik** [comment]
Ahhhhh -- ok! so the population sampler (i.e. [here](https://github.com/TomWagg/cosmic-gala/blob/ded42d8885f78a9b7d09bcfcec1c56a3de87f25f/kicker/pop.py#L206)) assigns `tphysf` by setting `SF_start` and `SF_duration`. I *think* you should be able to just recast `tphysf` with the true ages (and do the same thing with the metallicity as well by recasting `metallicity`) in the initialbinaries DataFrame.

**Comment by TomWagg** [comment]
Okay so I _think_ this is approximately what I tried but it gave me strange results (bpp only having one line per binary). I set the metallicities [here](https://github.com/TomWagg/cosmic-gala/blob/ded42d8885f78a9b7d09bcfcec1c56a3de87f25f/kicker/pop.py#L240) and I test changing `tpyhs` [here](https://github.com/TomWagg/cosmic-gala/blob/ded42d8885f78a9b7d09bcfcec1c56a3de87f25f/kicker/pop.py#L245-L246) with a toggle for comparing
