### ISSUE TITLE
Create a population of binaries from 'recent' history

### ISSUE THREAD

**Issue by TomWagg** [TomWagg/cosmic-gala#17]
Run a fairly large population through the entire code to get the recent history of the Milky Way.

- Restrict lookback times to < 200 Myr
    - This will limit us to the low-alpha disc based on Neige's model
- Remove any sort of mass cut
- Binary fraction = 1.0
   - This still bothers me a bit, since we're allowing any mass

It may be useful to actually
- [x] estimate how large the population should be (or at least how much star forming mass came) from the last 200 Myr

**Comment by katiebreivik** [comment]
@TomWagg: we can definitely talk more about the binary fraction normalizations when I'm back at CCA tomorrow! Normalizing to a different binary fraction (including a mass and even metallicity dependent one) can be done in post processing since we only care about the massive stars right now.
