### ISSUE TITLE
Transform simulated binaries into observables

### ISSUE THREAD

**Issue by TomWagg** [TomWagg/cosmic-gala#19]
Katie has [a bunch of useful code](https://github.com/katiebreivik/rando-gaia-scripts) for getting Gaia observables from our simulated binaries. This will account for dust extinction and bolometric corrections and stuff. Seems like I'll just need to find some MIST isochrones and it's all there to work.

- [x] Integrate Katie's code into the package (`observables.py`? easy access functions in `Population`?)
- [x] Grab those isochrones from somewhere

The result of all of this should be some magnitude of the object I think.

**Comment by katiebreivik** [comment]
Once you install [isochrones](https://isochrones.readthedocs.io/en/latest/install.html), you can use the [bolometric correction grid module](https://isochrones.readthedocs.io/en/latest/bc.html) to get the `bc_grid`. Since we'll be using Gaia and 2MASS filters, I would include: `['J', 'H', 'K', 'G', 'BP', 'RP']` for now.

**Comment by TomWagg** [comment]
Thanks @katiebreivik! I had some questions about the scripts (just want to make sure I understand what's going on 🙂):

1. Absolute bolometric luminosity function
As ever I know literally no astronomy so had to google how one calculates this. It seems the most recent definition sets $M_{\rm bol} = -2.5 \log_{10}(L / L_0)$ where $L_0 = 3.0128\times10^{28} \, {\rm W}$. This seems to give slightly different values that the function [that you have](https://github.com/katiebreivik/rando-gaia-scripts/blob/main/phot_helpers.py#L33). Is this purposeful (maybe the packages use an older definition)?

2. SkyCoord settings
Why do you change the `galcen_distance` and `z_sun` values ([here](https://github.com/katiebreivik/rando-gaia-scripts/blob/main/phot_helpers.py#L148-L149))?

3. `Av` cut
What does [this bit](https://github.com/katiebreivik/rando-gaia-scripts/blob/main/phot_helpers.py#L224-L225) do? Why the number 6?

4. `sys_type==2`?
I thought that this meant a BH binary but it seems like it just ignores the primary and looks at the secondary? Instead of these `sys_types` could I just check which of the components are stars (also WDs? Or just like kstar 1-9?) and whether they are bound and then treat them accordingly?

p.s. very much **not** expecting a weekend reply, just bored and stuck in a hotel so figured I might as well be productive and get this ready for next week 🙃

**Comment by TomWagg** [comment]
This seems to be working! 🎉 Here's a plot of the apparent G band magnitude vs. distance, coloured by luminosity of the brighter star with points that have sizes reflecting their relative masses!

![image](https://user-images.githubusercontent.com/21990332/193469053-7f93329f-428e-43fa-98a0-e920f55e79e8.png)

**Comment by TomWagg** [comment]
I'm going to leave this open for now until we discuss my questions above but if my guesses were correct then this may be all done 🙂
