### ISSUE TITLE
Bayestar dustmap lacks coverage in some areas - how do we handle this?

### ISSUE THREAD

**Issue by TomWagg** [TomWagg/cosmic-gala#27]
I was chatting with Katie about this and she says we'll need to get an opinion from @adrn.

**44% of systems** in my latest simulation fall outside of the range of the bayestar dustmap. It seems that this map only covered "[the three quarters of the sky north of a declination of -30°](https://dustmaps.readthedocs.io/en/latest/maps.html#bayestar)". The systems that are missed all have declinations lower than this.

What should we do about this? (Currently my default is to conservatively assume maximum dust extinction for all of these objects.)

- Is there an alternate dustmap?
- Katie suggested maybe [mwdust](https://github.com/jobovy/mwdust) could help?
- Could we do something smart for missing areas (maybe find an equivalent point reflected about the galactic plane??)

**Comment by mathren** [comment]
mmh...The Zari+21 sample is cut (from sec. 3 onwards) to |b| < 25. How many systems do you lose applying that cut? Would that alleviate the problem?

I think many interesting science cases come from the outliers cut out, but for the purpose of anchoring the simulations this may be a sensible first step to try.

**Comment by adrn** [comment]
Yes this is a limitation of the existing precise 3D dust maps that we just have to live with. For comparing to actual data, if we want to be precise, we can just cut the data to be dec > -30º and do the comparison to your simulated sample for those systems. For playing around, you could do the "reflect in galactic latitude / b" trick you alluded to above or use the stitched dust map in mwdust.

**Comment by adrn** [comment]
Oh, you could also try this dustmap but I've never worked with it: https://ui.adsabs.harvard.edu/abs/2020A%26A...639A.138L/abstract

**Comment by TomWagg** [comment]
Thanks guys! If I just cut everything below -30 dec then the ~3300 systems matching OBA mask become ~2500 systems so not a huge impact.

But the Leike dustmap is intriguing @adrn because that's [already in dustmaps](https://dustmaps.readthedocs.io/en/latest/maps.html#leike-glatzle-enszlin-2020) it seems. I'd dismissed at first because it was a box and I thought that wasn't as deep or something. But I guess we just care about dust along the line of sight and so it's okay to just focus on the close stuff?

Either way that's super easy to try so I'll download and use that one then report back.

**Comment by TomWagg** [comment]
Still considering the best way to go forward with this. I've tested using SFD/the Leike map for declinations < -30 and that works fine.

But I think @adrn mentioned that there was something smarter we could do when using Leike. My understanding was this: since it is a box that only goes out to a certain distance, it's only a lower bound on the extinction. We need to add SFD to it to get the full extinction. But we need to only add the part of SFD that comes from outside the range covered by the Leike map.

Annnnd I don't really understand how to do that when the SFD map is only 2D? I think you mentioned integrating something but I'm not sure what? Feel free to just direct me to go read something!

**Comment by adrn** [comment]
Ha, I'm not sure it was "smarter," but the idea would be to use a 2D dust map as the asymptotic value for a more local 3D dust map. But I'm actually not sure how that will work, so I think the practical solutions are to use bayestar and either:
(1) fill the missing dust map with symmetric (w.r.t. galactic plane) sky fields,
(2) cut the data to dec > -30º and only work there
Since we aren't trying to reproduce the data *exactly* (only in a statistical sense), I think either would be fine.

**Comment by TomWagg** [comment]
Haha okay gotcha. In that case I'll try doing the symmetric thing in that case, _should_ be fairly simple with astropy coordinates! 🙂
