### ISSUE TITLE
How are low-mass binaries getting ejected from the galaxy?

### ISSUE THREAD

**Issue by TomWagg** [TomWagg/cosmic-gala#4]
This'll be a question for @adrn.

I'm seeing that some low-mass binaries are managing to get ejected from the galaxy. Perhaps some sort of interaction is happening in the centre in `gala`?

Here are some plots of the orbit of one particular binary at 50 Myr, 200 Myr, 2Gyr and 10Gyr.

![image](https://user-images.githubusercontent.com/21990332/192121338-cbbe738f-f1ed-4c29-bf15-eb3cd521c225.png)
![image](https://user-images.githubusercontent.com/21990332/192121344-bbdfe489-edad-405f-8931-c03edbb7aad9.png)
![image](https://user-images.githubusercontent.com/21990332/192121345-faf95038-524e-43f8-bbed-3ba7c4dba013.png)
![image](https://user-images.githubusercontent.com/21990332/192121346-a3213cd0-6eee-4e16-a971-c252cab569fb.png)

**Comment by adrn** [comment]
For the first one: this definitely does not have a small enough step size -- any time you see straight lines in an integrated orbit, that is bad :)

For the others: what integrator are you using? Can you point me to the code that calls `integrate_orbit()`?

**Comment by TomWagg** [comment]
Haha ah make sense 😬 I'm just using 1 Myr by default but maybe I need to make it small if they are closer to the centre?

Unsure, so whatever the default is I think. [Here's a link](https://github.com/TomWagg/cosmic-gala/blob/main/kicker/kicks.py#L105) to the code

**Comment by adrn** [comment]
Ah, ok yea I would use a smaller timestep for orbits with R < 1 kpc (maybe 0.2 Myr?). But I would also switch to an adaptive integrator -- you can do that with:

```python
import gala.integrate as gi
...integrate_orbit(..., Integrator=gi.DOPRI853Integrator)
```
to switch to an 8th order Runge–Kutta method (default is Leapfrog). http://gala.adrian.pw/en/latest/integrate/index.html#classes

**Comment by TomWagg** [comment]
Gotcha, I'm on it! And the adaptive integrator here means that it will change the timesteps to be even smaller if necessary?

**Comment by adrn** [comment]
Exactly, yea -- it will notice if there is significant energy loss in the orbit and adapt the stepsize. Only the DOPRI853 integrator does that though.

**Comment by TomWagg** [comment]
Circling back to this - in the latest simulation that I did there are no weird outliers in the non-kicked systems having switching to the adaptive integrator 🙂 So I'm going to close this issue!

![image](https://user-images.githubusercontent.com/21990332/194589408-da5eee20-12aa-4815-8a40-bc3d0d3bb05c.png)
